config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/welcome', to: 'welcome#index'

  resources :sessions, only: [:new, :create, :destroy]

  resources :artists do
    resources :shows
  end

  resources :fans

  # many to many for shows and artists????
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_secure_password

  has_many :shows
end

app/models/fan.rb
class Fan < ActiveRecord::Base
  has_secure_password
end

app/models/show.rb
class Show < ActiveRecord::Base
  belongs_to :artist

  # Use Chronic gem for natural language date and time entry

  # Shows migration is currently rolled back
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	def index
		@artists = Artist.all
	end

	def new
		@artist = Artist.new
	end

	def create
		@artist = Artist.new(artist_params)
		if @artist.save
			session[:user_id] = @artist.id
			session[:user_type] = "artist"
			redirect_to artist_path(@artist)
		else
			@errors = @artist.errors.full_messages
			render :new
		end
	end

	def show
		@artist = Artist.find(params[:id])
	end

	def update
		@artist = Artist.find(params[:id])
		@artist.update(artist_params)
		if @artist.update
			redirect_to artist_path
		else
			@errors = @artist.errors.full_messages
			render :edit_artist_path
		end
	end

	private
		def artist_params
			params.require(:artist).permit(:name, :email, :location, :photo_url, :bio, :password)
		end
end

app/controllers/fans_controller.rb
class FansController < ApplicationController

  def index
    @fans = Fan.all
  end

  def new
    @fan = Fan.new
  end

  def create
    @fan = Fan.new(fan_params)
    if @fan.save
      session[:user_id] = @fan.id
      session[:user_type] = "fan"
      redirect_to fan_path(@fan)
    else
      @errors = @fan.errors.full_messages
      render :new
    end
  end

  def show
    @fan = Fan.find(params[:id])
  end

  def update
    @fan = Fan.find(params[:id])
		@fan.update(fan_params)
		if @fan.update
			redirect_to fan_path
		else
			@errors = @fan.errors.full_messages
			render :edit_artist_path
    end
  end

  private

  def fan_params
    params.require(:fan).permit(:name, :username, :email, :password, :location, :bio, :photo_url)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if params[:user_type] == "artist"
      @user = Artist.find_by(email: params[:email])
      user_redirect = artist_path(@user)
    elsif params[:user_type] == "fan"
      @user = Fan.find_by(email: params[:email])
      user_redirect = fan_path(@user)
    end

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      session[:user_type] = params[:user_type]
      redirect_to user_redirect
    else
      @error = "Your login credentials were invalid"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    session[:user_type] = nil
    redirect_to root_path
  end

end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :find_headliner

  def index
    @shows = Show.all
  end

  def new
    @artist.shows.new
  end

  def create
    @show = @artist.shows.new(show_params)
    if @show.save
      redirect_to artist_path(@artist)
    else
      render :new
    end
  end

  private
    def find_headliner
      @artist = @current_artist
    end

    def show_params
      params.require(:show).permit(:date, :time, :venue, :city)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
  def current_artist
    @current_artist ||= Artist.find_by(id: session[:user_id])
  end

  def current_fan
    @current_fan ||= Fan.find_by(id: session[:user_id])
  end

  def artist_logged_in?
    !current_artist.nil?
  end

  def fan_logged_in?
    !current_fan.nil?
  end

  def authorize!
    redirect_to new_session_path unless logged_in?
  end

   def authenticate(password)
    self.password == password
  end
end

app/views/artists/new.html.erb
<div class="container">

  <h3>Register as an artist below</h3>

  <%= form_for @artist, :html => { :class => "form-horizontal" } do |f|%>
    <div class="form-group">
      <%= f.label :name, :html => { :class => "col-sm-2 control-label" } %>
      <%= f.text_field :name, :html => { :class => "form-control" } %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email%>
    </div>

    <div class="form-group">
      <%= f.label :location %>
      <%= f.text_field :location %>
    </div>

    <div class="form-group">
      <%= f.label :photo_url %>
      <%= f.text_field :photo_url %>
    </div>

    <div class="form-group">
      <%= f.label :bio %>
      <%= f.text_area :bio %>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <%= f.submit %>
  <% end %>

</div>

app/views/artists/show.html.erb
<div class="container">
  <div class="row">
    <div class="artist-photo col-md-3">
      <%= image_tag(@artist.photo_url, :html => { :class => "img-responsive"})  %>
    </div>

    <div class="artist-details col-md-3">
      <h2><%= @artist.name %></h2><br>
      <h3><%= @artist.email %></h3><br>
      <h4><%= @artist.location %></h4><br>
    </div>

    <div class="artist-bio col-md-4">
      <h4>Artist Biography</h4>
      <p>
        <% 30.times do %>
        <%= @artist.bio %>
        <% end %>
      </p>
    </div>
  </div>

  <div class="row col-md-12">
    <div class="artist-followers col-md-4">
      <h4><%= "#{@artist.name}'s Followers" %></h4>
      <% 10.times do %>
      <p class="artist-follower"> <%= "Artist follower" %> </p>
      <% end %>
    </div>

    <div class="artist-shows col-md-4">
      <h4><%= "#{@artist.name}'s Upcoming Shows" %></h4>
      <% if @current_artist %>
        <%= link_to("Add a new show!", new_artist_show_path(@current_artist)) %>
      <% end %>
      <% 5.times do %>
      <p class="artist-follower"> <%= "Artist show" %> </p>
      <% end %>
    </div>
  </div>
</div>

app/views/fans/new.html.erb
<div class="container">

  <div>
    <h3 class="text-center">Register as a fan below:</h3>
  </div>

  <%= form_for(@fan, html: {class: 'form-horizontal'}) do |f| %>

  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="form-group">
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </div>

  <div class="form-group">
    <%= f.label :photo_url %>
    <%= f.text_field :photo_url %>
  </div>

  <div class="form-group">
    <%= f.submit %>
  </div>

  <% end %>
</div>

app/views/fans/show.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-3 artist-photo">
      <%= image_tag(@fan.photo_url, :html => { :class => "img-responsive"}, size: "250x250")  %>
    </div>

    <div class="text-left col-md-3 artist-name">
      <h2><%= @fan.first_name %> <%= @fan.last_name %></h2>
      <h3><%= @fan.location %></h3>
    </div>

    <div class="col-md-4 artist-bio">
      <h3>Bio:</h3>
      <% 30.times do %>
        <span><%= @fan.bio %>. </span>
      <% end %>
    </div>
  </div>

  <div class="row col-md-12">
    <div class="col-md-3 fan-followings">
      <h3 class="text-center">Bands you're following:</h3>
      <% 10.times do %>
      <p class="text-center"><%= "Artist you follow" %> </p>
      <% end %>
    </div>

    <div class="col-md-3 fan-followings">
      <h3 class="text-center">Bands you may be interested in:</h3>
      <% 10.times do %>
      <p class="text-center"><%= "Interesting Artist" %> </p>
      <% end %>
    </div>

    <div class="col-md-3 fan-followings">
      <h3 class="text-center">Upcoming Shows:</h3>
      <% 10.times do %>
      <p class="text-center"><%= "Upcoming Show" %> </p>
      <% end %>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>ArtistRegistry</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
  <header class="header-nav">
    <h1>Artist Registry</h1>
    <h3>Connecting bands with their fans</h3>
    <% if current_artist %>
      Welcome, <%= link_to current_artist.email, artist_path(current_artist) %>
      //
      <%= link_to "Logout", session_path(current_artist), method: :delete %>
    <% elsif current_fan %>
      <%= link_to current_fan.email, fan_path(current_fan) %>
      <%= link_to "Logout", session_path(current_fan), method: :delete %>
    <% end %>
  </header>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div class="container text-center">
	<br>
	<div class="login">
		<h4>Log In Here</h4>
		<br>
		<%= render 'sessions/form' %>
	</div>
	<br>
	<div class="register">
		<%= link_to('Register As An Artist', '/artists/new') %>
		//
		<%= link_to('Register As A Fan', '/fans/new') %>
	</div>

</div>